#include "app/LanguageManager.h"
#include <cstring>

const char* LanguageManager::CardName(const std::string& id) const {
    struct Entry { const char* id; const char* en; const char* zh; };
    static const Entry table[] = {
        {"simple_test",    "Grayscale Test",       u8"灰度测试"},
        {"bloom",          "Bloom",                u8"泛光"},
        {"blur",           "Gaussian Blur",        u8"高斯模糊"},
        {"sharpen",        "Sharpen",              u8"锐化"},
        {"edge_detect",    "Edge Detection",       u8"边缘检测"},
        {"emboss",         "Emboss",               u8"浮雕"},
        {"pixelate",       "Pixelate",             u8"像素化"},
        {"vignette",       "Vignette",             u8"暗角"},
        {"chromatic",      "Chromatic Aberration", u8"色差"},
        {"color_grade",    "Color Grading",        u8"调色"},
        {"noise",          "Noise Generator",      u8"噪声生成"},
        {"kaleidoscope",   "Kaleidoscope",         u8"万花筒"},
        {"glitch",         "Glitch Art",           u8"故障艺术"},
        {"toon",           "Toon Shading",         u8"卡通着色"},
        {"vhs",            "VHS Retro",            u8"VHS 复古"},
        {"crt",            "CRT Monitor",          u8"CRT 显示器"},
        {"water_ripple",   "Water Ripple",         u8"水波纹"},
        {"lens_distort",   "Lens Distortion",      u8"镜头畸变"},
        {"xpl_glitch_screen_jump",      "Screen Jump",        u8"屏幕跳跃"},
        {"xpl_glitch_screen_shake",     "Screen Shake",       u8"屏幕震动"},
        {"xpl_glitch_scan_line_jitter", "Scan Line Jitter",   u8"扫描线抖动"},
        {"xpl_glitch_rgb_split_v4",     "RGB Split V4",       u8"RGB分离 V4"},
        {"xpl_glitch_rgb_split_v2",     "RGB Split V2",       u8"RGB分离 V2"},
        {"xpl_glitch_analog_noise",     "Analog Noise",       u8"模拟信号噪声"},
        {"xpl_glitch_image_block_v3",   "Image Block V3",     u8"画面块错位 V3"},
        {"xpl_glitch_image_block_v4",   "Image Block V4",     u8"画面块错位 V4"},
        {"xpl_glitch_tile_jitter",      "Tile Jitter",        u8"瓦片抖动"},
        {"xpl_glitch_rgb_split_v3",     "RGB Split V3",       u8"RGB分离 V3"},
        {"xpl_glitch_digital_stripe",   "Digital Stripe",     u8"数字条纹"},
        {"xpl_glitch_image_block_v2",   "Image Block V2",     u8"画面块错位 V2"},
        {"xpl_glitch_image_block_v1",   "Image Block V1",     u8"画面块错位 V1"},
        {"xpl_glitch_rgb_split_v1",     "RGB Split V1",       u8"RGB分离 V1"},
        {"xpl_glitch_rgb_split_v5",     "RGB Split V5",       u8"RGB分离 V5"},
        {"xpl_glitch_line_block",       "Line Block",         u8"行块错位"},
        {"xpl_glitch_wave_jitter",      "Wave Jitter",        u8"波浪抖动"},
        {"xpl_blur_bokeh", "散景模糊", u8"散景模糊"},
        {"xpl_blur_box", "方框模糊", u8"方框模糊"},
        {"xpl_blur_directional", "定向模糊", u8"定向模糊"},
        {"xpl_blur_dual_box", "双重方框模糊", u8"双重方框模糊"},
        {"xpl_blur_dual_gaussian", "双重高斯模糊", u8"双重高斯模糊"},
        {"xpl_blur_dual_kawase", "双重Kawase模糊", u8"双重Kawase模糊"},
        {"xpl_blur_dual_tent", "双重帐篷模糊", u8"双重帐篷模糊"},
        {"xpl_blur_gaussian", "高斯模糊", u8"高斯模糊"},
        {"xpl_blur_grainy", "颗粒模糊", u8"颗粒模糊"},
        {"xpl_blur_iris", "光圈模糊", u8"光圈模糊"},
        {"xpl_blur_iris_v2", "光圈模糊 V2", u8"光圈模糊 V2"},
        {"xpl_blur_kawase", "Kawase 模糊", u8"Kawase 模糊"},
        {"xpl_blur_radial", "径向模糊", u8"径向模糊"},
        {"xpl_blur_radial_v2", "径向模糊 V2", u8"径向模糊 V2"},
        {"xpl_blur_tent", "帐篷模糊", u8"帐篷模糊"},
        {"xpl_blur_tilt_shift", "移轴模糊", u8"移轴模糊"},
        {"xpl_blur_tilt_shift_v2", "移轴模糊 V2", u8"移轴模糊 V2"},
        {"xpl_color_bleach_bypass", "漂白旁路", u8"漂白旁路"},
        {"xpl_color_brightness", "亮度", u8"亮度"},
        {"xpl_color_contrast", "对比度", u8"对比度"},
        {"xpl_color_contrast_v2", "对比度 V2", u8"对比度 V2"},
        {"xpl_color_contrast_v3", "对比度 V3", u8"对比度 V3"},
        {"xpl_color_hue", "色相", u8"色相"},
        {"xpl_color_lens_filter", "镜头滤镜", u8"镜头滤镜"},
        {"xpl_color_saturation", "饱和度", u8"饱和度"},
        {"xpl_color_technicolor", "Technicolor", u8"Technicolor"},
        {"xpl_color_tint", "色调", u8"色调"},
        {"xpl_color_white_balance", "白平衡", u8"白平衡"},
        {"xpl_color_replace", "颜色替换", u8"颜色替换"},
        {"xpl_color_replace_v2", "颜色替换 V2", u8"颜色替换 V2"},
        {"xpl_edge_roberts", "Roberts 边缘", u8"Roberts 边缘"},
        {"xpl_edge_roberts_neon", "Roberts 霓虹", u8"Roberts 霓虹"},
        {"xpl_edge_roberts_neon_v2", "Roberts 霓虹 V2", u8"Roberts 霓虹 V2"},
        {"xpl_edge_scharr", "Scharr 边缘", u8"Scharr 边缘"},
        {"xpl_edge_scharr_neon", "Scharr 霓虹", u8"Scharr 霓虹"},
        {"xpl_edge_scharr_neon_v2", "Scharr 霓虹 V2", u8"Scharr 霓虹 V2"},
        {"xpl_edge_sobel", "Sobel 边缘", u8"Sobel 边缘"},
        {"xpl_edge_sobel_neon", "Sobel 霓虹", u8"Sobel 霓虹"},
        {"xpl_edge_sobel_neon_v2", "Sobel 霓虹 V2", u8"Sobel 霓虹 V2"},
        {"xpl_pixel_circle", "圆形像素化", u8"圆形像素化"},
        {"xpl_pixel_diamond", "菱形像素化", u8"菱形像素化"},
        {"xpl_pixel_hexagon", "六边形像素化", u8"六边形像素化"},
        {"xpl_pixel_hexagon_grid", "六边形网格", u8"六边形网格"},
        {"xpl_pixel_leaf", "叶片像素化", u8"叶片像素化"},
        {"xpl_pixel_led", "LED 像素化", u8"LED 像素化"},
        {"xpl_pixel_quad", "方形像素化", u8"方形像素化"},
        {"xpl_pixel_sector", "扇形像素化", u8"扇形像素化"},
        {"xpl_pixel_triangle", "三角形像素化", u8"三角形像素化"},
        {"xpl_vignette_aurora", "极光暗角", u8"极光暗角"},
        {"xpl_vignette_old_tv", "老电视暗角", u8"老电视暗角"},
        {"xpl_vignette_old_tv_v2", "老电视暗角 V2", u8"老电视暗角 V2"},
        {"xpl_vignette_rapid", "快速暗角", u8"快速暗角"},
        {"xpl_vignette_rapid_v2", "快速暗角 V2", u8"快速暗角 V2"},
        {"xpl_sharpen_v1", "锐化 V1", u8"锐化 V1"},
        {"xpl_sharpen_v2", "锐化 V2", u8"锐化 V2"},
        {"xpl_sharpen_v3", "锐化 V3", u8"锐化 V3"},
    };
    for (const auto& e : table) {
        if (id == e.id) return m_lang == Language::Chinese ? e.zh : e.en;
    }
    return id.c_str(); // fallback: return the id itself
}

const char* LanguageManager::CardDesc(const std::string& id) const {
    struct Entry { const char* id; const char* en; const char* zh; };
    static const Entry table[] = {
        {"simple_test",    "Basic grayscale shader, validates render pipeline",           u8"基础灰度着色器，验证渲染管线"},
        {"bloom",          "Extract bright areas with blur overlay for dreamy glow",     u8"提取高亮区域叠加模糊，产生梦幻光晕"},
        {"blur",           "Multi-pass separable Gaussian blur, large radius soft focus", u8"多通道可分离高斯模糊，大半径柔焦"},
        {"sharpen",        "Unsharp mask image sharpening, enhances edge detail",        u8"反锐化掩模图像锐化，增强边缘细节"},
        {"edge_detect",    "Sobel edge detection with optional normal visualization",     u8"Sobel 边缘检测，可选法线可视化"},
        {"emboss",         "Emboss filter for relief texture effect",                   u8"浮雕滤镜，产生浮雕纹理效果"},
        {"pixelate",       "Adjustable mosaic pixelation block size",                   u8"可调马赛克像素化块大小"},
        {"vignette",       "Darken edges to focus on center subject",                   u8"压暗边缘以突出中心主体"},
        {"chromatic",      "RGB channel offset simulating chromatic distortion",         u8"RGB 通道偏移模拟色差畸变"},
        {"color_grade",    "LUT-based cinematic color grading",                         u8"基于 LUT 的电影级调色"},
        {"noise",          "Perlin noise with adjustable frequency and amplitude",       u8"可调频率和振幅的 Perlin 噪声"},
        {"kaleidoscope",   "Radial symmetry with adjustable sectors and rotation",       u8"可调扇区和旋转的径向对称"},
        {"glitch",         "Digital glitch with random block shift and color tearing",    u8"随机块位移和色彩撕裂的数字故障"},
        {"toon",           "Cartoon-style color quantization, cel shading",              u8"卡通风格色彩量化，赛璐珞着色"},
        {"vhs",            "VHS tape scanlines, noise and color drift",                  u8"VHS 磁带扫描线、噪声和色彩漂移"},
        {"crt",            "CRT scanlines + phosphor RGB pattern + screen curvature",   u8"CRT 扫描线 + 磷光 RGB 图案 + 屏幕弯曲"},
        {"water_ripple",   "Normal-map based water ripple displacement",                 u8"基于法线贴图的水波纹位移"},
        {"lens_distort",   "Barrel/pincushion lens distortion correction",              u8"桶形/枕形镜头畸变校正与模拟"},
        {"xpl_glitch_screen_jump",      "Horizontal/vertical scrolling jump",                  u8"画面沿水平/垂直方向持续滚动跳跃，模拟信号中断"},
        {"xpl_glitch_screen_shake",     "Random screen shake, earthquake effect",              u8"随机屏幕抖动，模拟手持摄影晃动或地震效果"},
        {"xpl_glitch_scan_line_jitter", "Horizontal scan line random jitter",                  u8"水平扫描线随机左右位移，CRT 信号干扰风格"},
        {"xpl_glitch_rgb_split_v4",     "Time-quantized noise RGB channel split",              u8"时间步长量化随机噪声，红蓝通道分离色彩偏移"},
        {"xpl_glitch_rgb_split_v2",     "4-sine product organic chromatic aberration",         u8"四层正弦波叠加驱动红蓝位移，有机脉动色散"},
        {"xpl_glitch_analog_noise",     "Analog static noise with luminance jitter",           u8"模拟老旧电视雪花噪点，亮度抖动+彩色随机噪点"},
        {"xpl_glitch_image_block_v3",   "Single-layer block displacement + RGB split",         u8"方块网格切分画面，每块随机水平错位并分离 RGB"},
        {"xpl_glitch_image_block_v4",   "Dual-axis block RGB split, per-block shifting",       u8"方块错位+双轴 RGB 分离，每个块内二维通道偏移"},
        {"xpl_glitch_tile_jitter",      "Alternating tile band jitter with frequency gating",  u8"水平条带分割画面，奇数偶数行交替左右抖动撕裂"},
        {"xpl_glitch_rgb_split_v3",     "Per-channel sine wave RGB split, 3 directions",       u8"三通道独立正弦偏移，支持水平/垂直/对角线模式"},
        {"xpl_glitch_digital_stripe",   "Noise-driven UV shifting, trash frame color",         u8"噪声驱动 UV 坐标偏移+可调色彩残帧条纹叠加"},
        {"xpl_glitch_image_block_v2",   "Single block layer displacement with fade control",   u8"单层方块网格错位+RGB 分裂，渐变强度精细可调"},
        {"xpl_glitch_image_block_v1",   "Dual block layer grid corruption + RGB split",        u8"双层方块网格叠加错位，双网格交错复杂块损坏"},
        {"xpl_glitch_rgb_split_v1",     "Classic sine-pulsing RGB split, center fading",       u8"经典正弦脉冲 RGB 分离，靠边越远偏移越大"},
        {"xpl_glitch_rgb_split_v5",     "Noise-driven cross-channel permutation RGB split",    u8"噪声交叉通道置换，各通道从不同噪声采样偏移"},
        {"xpl_glitch_line_block",       "Rhythmic line block + YUV chrominance distortion",    u8"节律行块位移+YUV 色度畸变，最复杂故障效果"},
        {"xpl_glitch_wave_jitter",      "Simplex-noise wave displacement + RGB split",         u8"Simplex 噪声波形曲面位移，逐行波浪状扭曲"},
        {"xpl_blur_bokeh", "散景模糊", u8"散景模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_box", "方框模糊", u8"方框模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_directional", "定向模糊", u8"定向模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_dual_box", "双重方框模糊", u8"双重方框模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_dual_gaussian", "双重高斯模糊", u8"双重高斯模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_dual_kawase", "双重Kawase模糊", u8"双重Kawase模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_dual_tent", "双重帐篷模糊", u8"双重帐篷模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_gaussian", "高斯模糊", u8"高斯模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_grainy", "颗粒模糊", u8"颗粒模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_iris", "光圈模糊", u8"光圈模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_iris_v2", "光圈模糊 V2", u8"光圈模糊 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_kawase", "Kawase 模糊", u8"Kawase 模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_radial", "径向模糊", u8"径向模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_radial_v2", "径向模糊 V2", u8"径向模糊 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_tent", "帐篷模糊", u8"帐篷模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_tilt_shift", "移轴模糊", u8"移轴模糊效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_blur_tilt_shift_v2", "移轴模糊 V2", u8"移轴模糊 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_bleach_bypass", "漂白旁路", u8"漂白旁路效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_brightness", "亮度", u8"亮度效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_contrast", "对比度", u8"对比度效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_contrast_v2", "对比度 V2", u8"对比度 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_contrast_v3", "对比度 V3", u8"对比度 V3效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_hue", "色相", u8"色相效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_lens_filter", "镜头滤镜", u8"镜头滤镜效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_saturation", "饱和度", u8"饱和度效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_technicolor", "Technicolor", u8"Technicolor效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_tint", "色调", u8"色调效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_white_balance", "白平衡", u8"白平衡效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_replace", "颜色替换", u8"颜色替换效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_color_replace_v2", "颜色替换 V2", u8"颜色替换 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_roberts", "Roberts 边缘", u8"Roberts 边缘效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_roberts_neon", "Roberts 霓虹", u8"Roberts 霓虹效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_roberts_neon_v2", "Roberts 霓虹 V2", u8"Roberts 霓虹 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_scharr", "Scharr 边缘", u8"Scharr 边缘效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_scharr_neon", "Scharr 霓虹", u8"Scharr 霓虹效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_scharr_neon_v2", "Scharr 霓虹 V2", u8"Scharr 霓虹 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_sobel", "Sobel 边缘", u8"Sobel 边缘效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_sobel_neon", "Sobel 霓虹", u8"Sobel 霓虹效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_edge_sobel_neon_v2", "Sobel 霓虹 V2", u8"Sobel 霓虹 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_circle", "圆形像素化", u8"圆形像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_diamond", "菱形像素化", u8"菱形像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_hexagon", "六边形像素化", u8"六边形像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_hexagon_grid", "六边形网格", u8"六边形网格效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_leaf", "叶片像素化", u8"叶片像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_led", "LED 像素化", u8"LED 像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_quad", "方形像素化", u8"方形像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_sector", "扇形像素化", u8"扇形像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_pixel_triangle", "三角形像素化", u8"三角形像素化效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_vignette_aurora", "极光暗角", u8"极光暗角效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_vignette_old_tv", "老电视暗角", u8"老电视暗角效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_vignette_old_tv_v2", "老电视暗角 V2", u8"老电视暗角 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_vignette_rapid", "快速暗角", u8"快速暗角效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_vignette_rapid_v2", "快速暗角 V2", u8"快速暗角 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_sharpen_v1", "锐化 V1", u8"锐化 V1效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_sharpen_v2", "锐化 V2", u8"锐化 V2效果，自动迁移自 X-PostProcessing-Library"},
        {"xpl_sharpen_v3", "锐化 V3", u8"锐化 V3效果，自动迁移自 X-PostProcessing-Library"},
    };
    for (const auto& e : table) {
        if (id == e.id) return m_lang == Language::Chinese ? e.zh : e.en;
    }
    return "";
}

const char* LanguageManager::TranslateCategory(const std::string& cat) const {
    if (cat == "Blur Effects")         return CategoryBlur();
    if (cat == "Pixelate Effects")     return CategoryPixelate();
    if (cat == "Edge Detection")       return CategoryEdge();
    if (cat == "Glitch Effects")       return CategoryGlitch();
    if (cat == "Color Adjustment")     return CategoryColorAdj();
    if (cat == "Vignette Effects")     return CategoryVignette();
    if (cat == "Image Processing")     return CategoryImageProc();
    if (cat == "Process Effects")      return CategoryProcess();
    return cat.c_str();
}
